### ISSUE TITLE
what is

### ISSUE THREAD

**Issue by p1020119** [horacio9a/chaturbate-anonymous#1]
File "cb.py", line 22
    print ' =>',(num+1),value[:-1]
              ^
SyntaxError: invalid syntax

**Comment by horacio9a** [comment]
In just uploaded version v.1.0.4 line 22 is: print " =>",(num+1),value[:-1]
I'm not sure it will help. Try also this version of line 22: print (" =>",(num+1),value[:-1])
... maybe help?
