### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by heloimnew** [horacio9a/chaturbate-anonymous#12]
![image](https://user-images.githubusercontent.com/49543338/107567455-b2527b00-6bb3-11eb-878f-89a79c2f71e7.png)
I don't know if this program is still updated, or if anyone can help but recently encountered this issue and don't know how to fix it. It occurs in all codes regardless of recording program. Any help would be appreciated, thanks!

**Comment by horacio9a** [comment]
I just update files for Python27 version. You can try v.1.1.1 and tell me
your impression.
