### ISSUE TITLE
offline model

### ISSUE THREAD

**Issue by Shuvescart** [horacio9a/chaturbate-anonymous#15]
hey horacio9a i need some help trouble shoting. i started getting the message of offline model like a week ago, if i try to get cb_online_wanted.txt it doesn't show any online model.

i'm kind of shure that it is a problem on my end and not in the scrip, i was just hoping that you could help me.... if it helps i still can use the cam4 script only the cb is failing

**Comment by heloimnew** [comment]
I'm also having the same issue. Any insight would be appreciated!
