### ISSUE TITLE
Help needed, thanks!

### ISSUE THREAD

**Issue by lolx331** [horacio9a/chaturbate-anonymous#16]
Hello,
long time script user, thank you for it, its awesome!

Used it for a long time, tried to get back to it a couple of days ago, but when I try to record I get this error. Im guessing it has something to do with the video storage place, i tried editing the config a few times, changing the folder with no succes. 
![113](https://user-images.githubusercontent.com/106156492/170025071-6a8d4ed1-5f26-4303-8b45-cb4510104f87.jpg)
Help? 

Thanks a lot!

**Comment by horacio9a** [comment]
Obviously there is some problem with the name of your download directory. Can you write the first line of your config3.ini
I for example use:
[folders]
output_folder: D:/Videos/Chaturbate/

**Comment by lolx331** [comment]
Hey, sure, here it is! 

[folders]
output_folder: C:\Videos\Chaturbate

I did create this specific folder, in this location, i also tried changing the location to different partitions and/or drives (creating respective folders) - still same error.

I tried with both "/" and " \ "

Thanks!

**Comment by horacio9a** [comment]
Try this:
[folders]
output_folder: C:/Videos/Chaturbate/

... you forget put last /  ... and also check directory permition for write

**Comment by lolx331** [comment]
Ok, so Ive made a new folder. Now it looks like this:
[folders]
output_folder: F:/CB/
![113](https://user-images.githubusercontent.com/106156492/170564947-c54a42be-9212-45e7-b84b-108e0b45d339.jpg)

Folder is not Read Only.

Same issue. Cant wrap my head around it.

**Comment by horacio9a** [comment]
![2022-05-26](https://user-images.githubusercontent.com/17076459/170574247-1a30016f-ea39-4fd5-96f8-360fb89b1d3c.jpg)

**Comment by lolx331** [comment]
So I tried with your own folder path..
Still nothing.
![113](https://user-images.githubusercontent.com/106156492/170575692-8fd8331e-39fa-4127-bad1-1490c336ff9f.jpg)

**Comment by lolx331** [comment]
I fixed it. It appears steamlink was broken, i reinstalled it now and it works.

**Comment by lolx331** [comment]
Thanks for the help!

**Comment by horacio9a** [comment]
I'm glad you were able to find where is mistake.
