### ISSUE TITLE
some questiones

### ISSUE THREAD

**Issue by p1020119** [horacio9a/chaturbate-anonymous#2]
1 .if  cap lots modls one time , i should put the models name to CB_URL.txt?orCB_Model.txt?and run cb.py?
2.does ffmpeg can caping lots model one time ? 
3 if i just cap a model , not sure online or not , i hope add online list.
4.when i run cb.py ,File "cb.py", line 22
print ' =>',(num+1),value[:-1]
^
SyntaxError: invalid syntax  i am on win10 x64.

5.  hope mfc and cb can cap together.

6.  [ 2017-09-03T230714] [ERROR] { Error: getaddrinfo ENOENT chaturbate.com:443
    at Object.exports._errnoException (util.js:1024:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'chaturbate.com',
  host: 'chaturbate.com',
  port: 443 }

**Comment by horacio9a** [comment]
I just uploaded version v.1.0.4 where now all 5 scripts using the same file with the cb model names CB_Model.txt (CB_URL.txt is removed).
I have Windows 7 32bit and I can't test on Windows 10 64bit.
Is there anyone who uses Windows 10 and there is no problem like this?
The main purpose of this script is the high-quality recording of certain models. 
It is possible to record more than one model at the same time and it is often necessary to start multiple copies of cba.bat.
I have a similar script for MFC and I may soon be here to post but I do not intend to link CB and MFC scripts to one.
